In [1]:
import pandas as pd

In [6]:
rng = pd.date_range("2024-01-01", periods=6, freq="D")
print(rng)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
s = pd.Series([10,12,98,11,13,8], index=rng)
display(s)

2024-01-01    10
2024-01-02    12
2024-01-03    98
2024-01-04    11
2024-01-05    13
2024-01-06     8
Freq: D, dtype: int64

In [8]:
display(s.rolling(window=3).mean())

2024-01-01          NaN
2024-01-02          NaN
2024-01-03    40.000000
2024-01-04    40.333333
2024-01-05    40.666667
2024-01-06    10.666667
Freq: D, dtype: float64

In [9]:
display(s.resample("W").sum())

2024-01-07    152
Freq: W-SUN, dtype: int64

In [10]:
df_datas = pd.DataFrame({'data_str': ['2024-01-01', '2024-01-02', '2024-01-03']})
df_datas['data'] = pd.to_datetime(df_datas['data_str'])

In [11]:
df_datas['dia_da_semana'] = df_datas['data'].dt.day_name()
df_datas['mes'] = df_datas['data'].dt.month
df_datas

     data_str       data dia_da_semana  mes
0  2024-01-01 2024-01-01        Monday    1
1  2024-01-02 2024-01-02       Tuesday    1
2  2024-01-03 2024-01-03     Wednesday    1