In [1]:
import pandas as pd

In [45]:
df = pd.DataFrame({
    "nome": ["Ana", "João", "Maria", "Pedro", "Sofia"],
    "idade": [28, 35, 22, 41, 30],
    "cidade": ["São Paulo", "Rio de Janeiro", "São Paulo", "Belo Horizonte", "Rio de Janeiro"]
})

In [4]:
display(df.head())

    nome  idade          cidade
0    Ana     28       São Paulo
1   João     25  Rio de Janeiro
2  Maria     22       São Paulo
3  Pedro     41  Belo Horizonte
4  Sofia     30  Rio de Janeiro

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nome    5 non-null      object
 1   idade   5 non-null      int64
 2   cidade  5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [13]:
display(df.describe())
display(df.cidade.describe())
display(df)

           idade
count   5.000000
mean   29.200000
std     7.259477
min    22.000000
25%    25.000000
50%    28.000000
75%    30.000000
max    41.000000

count             5
unique            3
top       São Paulo
freq              2
Name: cidade, dtype: object

    nome  idade          cidade
0    Ana     28       São Paulo
1   João     25  Rio de Janeiro
2  Maria     22       São Paulo
3  Pedro     41  Belo Horizonte
4  Sofia     30  Rio de Janeiro

count             5
unique            3
top       São Paulo
freq              2
Name: cidade, dtype: object

In [14]:
df["nome"].describe()

count       5
unique      5
top       Ana
freq        1
Name: nome, dtype: object

In [20]:
# df["nome"] = pd.to_numeric(df["nome"], errors="coerce")
df["cidade"] = df["cidade"].astype("category")

df.dtypes

nome        object
idade        int64
cidade    category
dtype: object

# Filtros

In [25]:
df_nome_idade = df[["nome", "idade"]]

In [29]:
display(df_nome_idade)

    nome  idade
0    Ana     28
1   João     25
2  Maria     22
3  Pedro     41
4  Sofia     30

In [42]:
display(df)
display(df.loc[1, "cidade"])
display(df.iloc[0, 1])

df_nome = df.set_index("nome")
display(df_nome)
display(df_nome.loc["Pedro"])

    nome  idade          cidade
0    Ana     28       São Paulo
1   João     25  Rio de Janeiro
2  Maria     22       São Paulo
3  Pedro     41  Belo Horizonte
4  Sofia     30  Rio de Janeiro

'Rio de Janeiro'

np.int64(28)

       idade          cidade
nome
Ana       28       São Paulo
João      25  Rio de Janeiro
Maria     22       São Paulo
Pedro     41  Belo Horizonte
Sofia     30  Rio de Janeiro

idade                 41
cidade    Belo Horizonte
Name: Pedro, dtype: object

In [46]:
maiores_30 = df.loc[df["idade"] > 30, ["nome", "idade"]]
maiores_30

    nome  idade
1   João     35
3  Pedro     41

In [48]:
sp = df.loc[df["cidade"] == "São Paulo", ["nome", "cidade"]]
sp

    nome     cidade
0    Ana  São Paulo
2  Maria  São Paulo